
### GET Status

GET http://localhost:1337/status HTTP/1.1
Accept: application/json
### Add A Product

POST http://localhost:1337/products HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "id": "999",
    "description": "Super cool thing you will want",
    "price": 20.99
}
